final initialQuotes = [
  "The best way to predict the future is to create it.",
  "Believe you can and you're halfway there.",
  "The only way to do great work is to love what you do.",
  "You can't teach an old dog new tricks.",
  "Do what you can, with what you have, where you are.",
  "You only live once, so don't waste your last moments wasting time.",
  "You have infinite greatness inside of you. Let it win over the BS."
  "You have infinite potential, but it's up to you to use it wisely.",
  "Your faith must be stronger than your fears.",
  "The most dangerous thing in life is not to trust your instincts.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Believe in yourself, you're stronger than you think.",
  "Believe in yourself, believe in yourself, believe in yourself.",
  "The greatest wealth you can ever have is within yourself.",
  "You are never too old to set another goal or dream a new dream.",
  "The key to success is to focus on what you can control.",
  "The only way to do great work is to love what you do.",
  "The greatest wealth you can ever have is within yourself.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "You must believe that everything you desire really is available to you and that you possess all the tools, power and permission to achieve it.",
  "Take big, audacious action in the direction of your dreams, and do not let the fact that you're wetting your pants stop you.",
  "Be grateful for all you are and all that you are becoming.",
  "One of the best things you can do to improve the world is to improve yourself.",
  "Trust yourself and your beliefs, and you'll never be disappointed.",
  "The most important thing in life is to enjoy every moment, to laugh, to love, and to keep smiling.",
  "Your support structure is the key to success.",
  "Your faith in God is the most powerful weapon you have.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Every day is a new beginning. Take a deep breath and start again.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Your attitude determines your direction.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "Don't watch the clock; do what it does. Keep going.",
  "The secret of getting ahead is getting started.",
  "Strive not to be a success, but rather to be of value.",
  "The mind is everything. What you think you become.",
  "Happiness is not something readymade. It comes from your own actions.",
  "The best revenge is massive success.",
  "It always seems impossible until it's done.",
  "Life is what happens to you while you're busy making other plans.",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
  "Everything you've ever wanted is on the other side of fear.",
  "Dream big and dare to fail.",
  "Don't sweat the small stuff... and it's all small stuff.",
  "In the grand scheme of things, almost nothing matters. Know what does matter.",
  "If you can't do anything about it, why worry?",
  "Will this matter in five years? If not, it's not worth worrying about now.",
  "Remind yourself that when you die, your 'In Basket' won't be empty.",
  "Learn to live in the present moment. It's the only moment you have.",
  "Ask yourself: 'Will this matter a year from now?'",
  "Choose being kind over being right and you'll be right every time.",
  "Your 'emergency' isn't usually other people's emergency.",
  "Surrender to the fact that life isn't fair.",
  "Allow yourself to be bored occasionally. Don't fill every moment with activity.",
  "Realize that life is a test. It is only a test.",
  "Remember that when you die, your 'to do' list won't be empty.",
  "Think of what you have instead of what you want.",
  "Practice humility. There's always someone better than you.",
  "Compliment three people every day.",
  "Watch a sunrise at least once a year.",
  "Overtip breakfast waitresses.",
  "Never waste an opportunity to tell someone you love them.",
  "Remember other people's birthdays.",
  "Leave everything a little better than you found it.",
  "Keep it simple.",
  "Think big thoughts but relish small pleasures.",
  "Become the most positive and enthusiastic person you know.",
  "Don't expect life to be fair.",
  "Never underestimate the power of forgiveness.",
  "Drink champagne for no reason at all.",
  "Live your life as an exclamation, not an explanation.",
  "Don't be afraid to say, 'I made a mistake.'",
  "Smile a lot. It costs nothing and is beyond price.",
  "Remember that winners do what losers don't want to do.",
  "Learn to listen. Opportunity sometimes knocks very softly.",
  "Never give up on anybody. Miracles happen every day.",
  "Be brave. Even if you're not, pretend to be. No one can tell the difference.",
  "Treat everyone you meet like you want to be treated.",
  "Be the change you wish to see in the world. - Mahatma Gandhi",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
  "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference. - Robert Frost",
  "Ask not what your country can do for you – ask what you can do for your country. - John F. Kennedy",
  "I have a dream that one day this nation will rise up and live out the true meaning of its creed. - Martin Luther King Jr.",
  "To be or not to be, that is the question. - William Shakespeare",
  "That's one small step for man, one giant leap for mankind. - Neil Armstrong",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
  "Imagination is more important than knowledge. - Albert Einstein",
  "I think, therefore I am. - René Descartes",
  "Stay hungry, stay foolish. - Steve Jobs",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "If you look at what you have in life, you'll always have more. - Oprah Winfrey",
  "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. - Mark Twain",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The only impossible journey is the one you never begin. - Tony Robbins",
  "Life is what happens to you while you're busy making other plans. - John Lennon",
  "Be brave. Even if you're not, pretend to be. No one can tell the difference.",
  "Treat everyone you meet like you want to be treated.",
  "You are responsible for what you say and do. You are not responsible for whether or not people freak out about it. - Jen Sincero, You Are a Badass",
  "If you're serious about changing your life, you'll find a way. If you're not, you'll find an excuse. - Jen Sincero, You Are a Badass",
  "What other people think about you has nothing to do with you and everything to do with them. - Jen Sincero, You Are a Badass",
  "You are perfect. To think anything less is as pointless as a river thinking that it's got too many curves or that it moves too slowly or that its rapids are too rapid. - Jen Sincero, You Are a Badass",
  "Nobody who ever accomplished anything big or new or worth raising a celebratory fist in the air did it from their comfort zone. - Jen Sincero, You Are a Badass",
  "Your life is your party. You get to choose how you invite people and experiences and things into it. - Jen Sincero, You Are a Badass",
  "You are loved. Massively. Ferociously. Unconditionally. The Universe is totally freaking out about how awesome you are. - Jen Sincero, You Are a Badass",
  "Deciding is freedom. Indecision is torture. - Jen Sincero, You Are a Badass",
  "Be the change you wish to see in the world. - Mahatma Gandhi",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
  "Share everything. - Inspired by Robert Fulghum",
  "Play fair and don't hit people. - Inspired by Robert Fulghum",
  "Clean up your own mess. - Inspired by Robert Fulghum",
  "Don't take things that aren't yours. - Inspired by Robert Fulghum",
  "Say you're sorry when you hurt somebody. - Inspired by Robert Fulghum",
  "Wash your hands before you eat. - Inspired by Robert Fulghum",
  "Flush. - Inspired by Robert Fulghum",
  "Warm cookies and cold milk are good for you. - Inspired by Robert Fulghum",
  "Live a balanced life - learn, think, draw, paint, sing, dance, play, and work every day. - Inspired by Robert Fulghum",
  "Take a nap every afternoon. - Inspired by Robert Fulghum",
  "When you go out into the world, watch out for traffic, hold hands, and stick together. - Inspired by Robert Fulghum",
  "Be aware of wonder. Remember the little seed in the plastic cup. - Inspired by Robert Fulghum",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
  "Take care of your body. It's the only place you have to live. - Jim Rohn",
  "The only bad workout is the one that didn't happen. - Unknown",
  "Fitness is not about being better than someone else. It's about being better than you used to be. - Unknown",
  "The difference between try and triumph is a little umph. - Marvin Phillips",
  "Your health is an investment, not an expense. - Unknown",
  "The hardest lift of all is lifting your butt off the couch. - Unknown",
  "Eat for the body you want, not for the body you have. - Unknown",
  "You don't have to be extreme, just consistent. - Unknown",
  "Your body can stand almost anything. It's your mind that you have to convince. - Unknown",
  "The only way to finish is to start. - Unknown",
  "Motivation is what gets you started. Habit is what keeps you going. - Jim Ryun",
  "You are what you eat, so don't be fast, cheap, easy, or fake. - Unknown",
  "Exercise is king. Nutrition is queen. Put them together and you've got a kingdom. - Jack LaLanne",
  "The only bad workout is the one that didn't happen. - Unknown",
  "Strive for progress, not perfection. - Unknown",
  "Guilt is not a response to anger; it is a response to one's own actions or lack of action. - Audre Lorde",
  "No amount of guilt can change the past, and no amount of worrying can change the future. - Unknown",
  "Think big thoughts, but relish small pleasures. - Unknown",
  "Take a brisk 30 minute walk everyday.",
  "Treat yourself to a massage on your birthday.",
  "Smile alot. It costs nothing and is beyond price.",
  "Know how to drive a stick shift.",
  "Keep your watch five minutes fast.",
  "Never deprive someone of hope, it might be all they have.",
  "Give yourself an hour to cool off before responding to someone who has provoked you.  If it involved something really important, give yourself overnight.",
  "Pay your bills on time.",
  "When playing games with children, let them win.",
  "Get acquainted with a good lawyer, doctor, accountant and plumber.",
  "Take time to smell the roses.",
  "Pray not for things, but for wisdom and courage.",
  "Don't waste time responding to your critics.",
  "Avoid negative people.",
  "Resist telling people how something should be done. Instead, tell them what needs to be done. They will often surprise you with creative solutions.",
  "Wear out, don't rust out.",
  "Do battle against prejudice and discrimination wherever you find it.",
  "Don't quit a job until you've lined up another.",
  "Never take action when you're angry.",
  "Become the most positive and enthusiastic person  you know.",
  "Be insatiably curious. Ask 'why' a lot.",
  "Don't forget, a person's greatest emotional need is to feel appreciated.",
  "Don't carry a grudge.",
  "Show respect for all living things.",
  "Loosen up. Relax. Except for rare life-and-death matters, nothing is as important as it first seems.",
  "Make allowances for incompetence.",
  "Get out of the grumble mode.",
];
